version: '3.3'
services:

  frontend:
    container_name: yandex_dimplom_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  backend:
    container_name: yandex_dimplom_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - staticfiles_value:/backend_foodgram_app/foodgram_app/static/
      - media_value:/backend_foodgram_app/foodgram_app/media/
      - ../backend:/backend_foodgram_app
    ports:
      - "8000:8000"
  nginx:
    container_name: yandex_dimplom_nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - staticfiles_value:/var/html/api/static/
      - media_value:/var/html/api/media/
    depends_on:
      - frontend

volumes:
  staticfiles_value:
  media_value:
